### ISSUE TITLE
Not working with tns 2.3.0 and Xcode 8 / iOS 10

### ISSUE THREAD

**Issue by DomGaud** [NathanWalker/nativescript-loading-indicator#14]
Receive the following error when running `tns run iOS --emulator` : 
`TypeError: UIApplication.sharedApplication is not a function.`

I have tested using both iOs 10 and iOS 9.1, but receive the same error. 

Full error message:
`ORIGINAL EXCEPTION: TypeError: UIApplication.sharedApplication is not a function. (In 'UIApplication.sharedApplication()', 'UIApplication.sharedApplication' is an instance of UIApplication)
    ORIGINAL STACKTRACE:
    _getRootWindow@file:///app/tns_modules/nativescript-loading-indicator/src/ios/mbprogress-hud.js:41:47
    show@file:///app/tns_modules/nativescript-loading-indicator/src/ios/mbprogress-hud.js:8:81`

**Comment by DomGaud** [comment]
There have been a number of changes in iOS sdk from using methods to properties.

**Solution** - change from using a method:

``` Javascript
return UIApplication.sharedApplication().windows[0];
```

to a property

``` Javascript
return UIApplication.sharedApplication.windows[0];
```

**Comment by blaur** [comment]
@DomGaud So what you are saying is to manually change it in the included node module lib?

**Comment by NathanWalker** [comment]
Fixed with `2.2.0` 👍
